/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprimerbimestre;

import java.text.DecimalFormat;

/**
 *
 * @author nivek
 */
public class PantallaInfoCuenta extends javax.swing.JFrame {
    Usuario cliente;
    int indiceDeCuenta;
    /**
     * Creates new form PantallaInfoCuenta
     */
    public PantallaInfoCuenta(Usuario cliente, int indice) {
        initComponents();
        DecimalFormat frmt=new DecimalFormat();
        frmt.setMaximumFractionDigits(2);
        this.cliente = cliente;
        this.indiceDeCuenta = indice;
        txtImgNumeroDeCuenta.setText("N°"+String.valueOf(cliente.getNumeroDeCuenta(indiceDeCuenta)));
        txtSaldoCuenta.setText("$ "+String.valueOf(frmt.format((long)cliente.getSaldo(indiceDeCuenta))));
        txtImgTipoDeCuenta.setText(String.valueOf(cliente.getTipoDeCuenta(indiceDeCuenta)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelFooterAzul = new javax.swing.JPanel();
        PanelFooterRojo = new javax.swing.JPanel();
        txtTituloInformacionCuenta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtImgTipoDeCuenta = new javax.swing.JLabel();
        txtSaldoDisponible = new javax.swing.JLabel();
        txtSaldoCuenta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imgTransferencia2 = new javax.swing.JLabel();
        txtTransMismoBanco = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imgTransferencia3 = new javax.swing.JLabel();
        txtTransMismoBanco1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        imgTransferencia4 = new javax.swing.JLabel();
        txtTransOtroBanco = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtImgNumeroDeCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFooterAzul.setBackground(new java.awt.Color(15, 34, 64));

        javax.swing.GroupLayout PanelFooterAzulLayout = new javax.swing.GroupLayout(PanelFooterAzul);
        PanelFooterAzul.setLayout(PanelFooterAzulLayout);
        PanelFooterAzulLayout.setHorizontalGroup(
            PanelFooterAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        PanelFooterAzulLayout.setVerticalGroup(
            PanelFooterAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(PanelFooterAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 280, 30));

        PanelFooterRojo.setBackground(new java.awt.Color(227, 29, 26));

        javax.swing.GroupLayout PanelFooterRojoLayout = new javax.swing.GroupLayout(PanelFooterRojo);
        PanelFooterRojo.setLayout(PanelFooterRojoLayout);
        PanelFooterRojoLayout.setHorizontalGroup(
            PanelFooterRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        PanelFooterRojoLayout.setVerticalGroup(
            PanelFooterRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(PanelFooterRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 280, 10));

        txtTituloInformacionCuenta.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        txtTituloInformacionCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloInformacionCuenta.setText("Información de la cuenta");
        jPanel1.add(txtTituloInformacionCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 260, -1));

        txtImgTipoDeCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImgTipoDeCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosYLogos/iconoBancoPequeño.png"))); // NOI18N
        txtImgTipoDeCuenta.setText("Ahorros");
        jPanel1.add(txtImgTipoDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, -1));

        txtSaldoDisponible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSaldoDisponible.setText("Saldo Disponible");
        jPanel1.add(txtSaldoDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, -1));

        txtSaldoCuenta.setFont(new java.awt.Font("Segoe UI Variable", 0, 48)); // NOI18N
        txtSaldoCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSaldoCuenta.setText("$ 458");
        jPanel1.add(txtSaldoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 280, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 222, 222)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgTransferencia2.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        imgTransferencia2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imgTransferencia2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosYLogos/iconoFlechasPequenio.png"))); // NOI18N
        jPanel2.add(imgTransferencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, 40));

        txtTransMismoBanco.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtTransMismoBanco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTransMismoBanco.setText("Transf. Cuenta propia");
        jPanel2.add(txtTransMismoBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 160, 38));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 222, 222)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgTransferencia3.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        imgTransferencia3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imgTransferencia3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosYLogos/iconoFlechasPequenio.png"))); // NOI18N
        jPanel3.add(imgTransferencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, 40));

        txtTransMismoBanco1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtTransMismoBanco1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTransMismoBanco1.setText("Transf. Banco del Búho");
        jPanel3.add(txtTransMismoBanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 160, 38));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 200, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 222, 222)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgTransferencia4.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        imgTransferencia4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imgTransferencia4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosYLogos/iconoFlechasPequenio.png"))); // NOI18N
        jPanel4.add(imgTransferencia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, 40));

        txtTransOtroBanco.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtTransOtroBanco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTransOtroBanco.setText("Transf. Otro Banco");
        jPanel4.add(txtTransOtroBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 160, 38));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, 40));

        jButton1.setBackground(new java.awt.Color(227, 29, 26));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 80, 30));

        txtImgNumeroDeCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImgNumeroDeCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosYLogos/iconoNumeros.png"))); // NOI18N
        txtImgNumeroDeCuenta.setText("N° 1324567856");
        jPanel1.add(txtImgNumeroDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInfoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInfoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInfoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInfoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInfoCuenta(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFooterAzul;
    private javax.swing.JPanel PanelFooterRojo;
    private javax.swing.JLabel imgTransferencia2;
    private javax.swing.JLabel imgTransferencia3;
    private javax.swing.JLabel imgTransferencia4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtImgNumeroDeCuenta;
    private javax.swing.JLabel txtImgTipoDeCuenta;
    private javax.swing.JLabel txtSaldoCuenta;
    private javax.swing.JLabel txtSaldoDisponible;
    private javax.swing.JLabel txtTituloInformacionCuenta;
    private javax.swing.JLabel txtTransMismoBanco;
    private javax.swing.JLabel txtTransMismoBanco1;
    private javax.swing.JLabel txtTransOtroBanco;
    // End of variables declaration//GEN-END:variables
}
